Change the behavior bin/dev_scripts/update-localization-files script.
With this change the script will only update the webwork2.pot file using
xgettext.pl by default.  It will not also update the .po files using
msgmerge.

However, there are now options for this script.  If you run the script
with no options it will do what is stated above.  If you add the option
`-p`, then it will also update all .po files.  If you instead use the
option `-l` with a language code, then it will update only that .po file
in addition to updating the webwork2.pot file.  For example if you run
`update-localization-files -l fr-CA`, then it will update the
webwork2.pot file, and then update the fr-CA.po file.

The point of this is that with the switch to using Transifex, we no
longer need to directly update po files.  We only need to update the
webwork2.pot file.  When those changes are merged into the develop
branch, then Transifex will automatically get those changes, and those
changes will be added to all of the languages there.  When Transifex
makes a pull request back to webwork2 for a language, those strings will
be included.

The optional flags are for translators.  If a translator wants to add
the current strings from the code to the po file so that they can start
working on translations before we merge the updated webwork2.pot file,
then they can use this script with the options to do so.

This also adds the conf directory to those xgettext.pl searches for
translation strings as is done in #1631 to make sure that gets into this
file in its new location.

diff --git a/bin/dev_scripts/update-localization-files b/bin/dev_scripts/update-localization-files
--- a/bin/dev_scripts/update-localization-files
+++ b/bin/dev_scripts/update-localization-files
@@ -1,5 +1,44 @@
 #!/bin/bash
 
+function print_help_exit
+{
+	printf "Usage: %s [options]\n" $(basename $0) >&2
+	printf " Update the webwork2.pot and language .po files with translation strings from the code.\n" >&2
+	printf "  options:\n" >&2
+	printf "    -p|--po-update  Update po files as well.  By default only the webwork2.pot file is updated.\n" >&2
+	printf "    -l|--langauge   Update the only given language in addition to updating the webwork2.pot file.\n" >&2
+	printf "    -h|--help       Show this help.\n" >&2
+	exit 1
+}
+
+TEMP=$(getopt -a -o pl:h -l po-update,language:,help -n "$(basename $0)" -- "$@")
+
+eval set -- "$TEMP"
+
+UPDATE_PO=false
+LANGUAGE=""
+
+while [ ! "$1" = "--" ]
+do
+	case "$1" in
+		-p|--po-update)
+			UPDATE_PO=true
+			shift 1
+			;;
+		-l|--language)
+			LANGUAGE=$2
+			shift 2
+			;;
+		-h|--help)
+			print_help_exit
+			;;
+		*)
+			echo "Internal error!"
+			exit 1
+			;;
+	esac
+done
+
 if [ -z "$WEBWORK_ROOT" ] || [ -z "$PG_ROOT" ]; then
     echo >&2 "You need to set both the WEBWORK_ROOT and PG_ROOT environment variables.  Aborting."
     exit 1
@@ -18,4 +57,9 @@ echo "Updating $WEBWORK_ROOT/webwork2.pot"
 
 xgettext.pl -o webwork2.pot -D $WEBWORK_ROOT/lib -D $WEBWORK_ROOT/conf -D $PG_ROOT/lib -D $PG_ROOT/macros
 
-find $LOCDIR -name '*.po' -exec bash -c "echo \"Updating {}\"; msgmerge -qUN {} webwork2.pot" \;
+if $UPDATE_PO; then
+	find $LOCDIR -name '*.po' -exec bash -c "echo \"Updating {}\"; msgmerge -qUN {} webwork2.pot" \;
+elif [[ $LANGUAGE != "" && -e "$LANGUAGE.po" ]]; then
+	echo "Updating $LOCDIR/$LANGUAGE.po"
+	msgmerge -qUN $LANGUAGE.po webwork2.pot
+fi
